CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS festivals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL DEFAULT '',
    start_date date NOT NULL,
    end_date date NOT NULL,
    city text NOT NULL DEFAULT '',
    region text NOT NULL DEFAULT '',
    latitude double precision NOT NULL DEFAULT 0,
    longitude double precision NOT NULL DEFAULT 0,
    image text NOT NULL DEFAULT '',
    website text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS breweries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL DEFAULT '',
    city text NOT NULL DEFAULT '',
    website text NOT NULL DEFAULT '',
    logo text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS festivals_breweries (
    festival_id bigint NOT NULL REFERENCES festivals(id) ON DELETE CASCADE,
    brewery_id bigint NOT NULL REFERENCES breweries(id) ON DELETE CASCADE,
    PRIMARY KEY (festival_id, brewery_id)
);

CREATE INDEX IF NOT EXISTS idx_festivals_start_date ON festivals(start_date);
CREATE INDEX IF NOT EXISTS idx_festivals_breweries_brewery_id ON festivals_breweries(brewery_id);
