name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: backend/go.sum

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Run backend tests
        run: cd backend && go test -v ./...

      - name: Run ESLint
        run: cd frontend && npx eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts

      - name: Check formatting with Prettier
        run: cd frontend && npx prettier --check src/

      - name: Run unit tests
        run: cd frontend && npm run test -- --run

      - name: Run unit tests with coverage
        run: cd frontend && npm run test:coverage -- --run

      - name: Type check
        run: cd frontend && npx vue-tsc -b --noEmit

      - name: Build project
        run: cd frontend && npm run build

      - name: Install Playwright Browsers
        run: cd frontend && npx playwright install --with-deps firefox

      - name: Run E2E tests
        run: cd frontend && npm run test:e2e
        env:
          VITE_API_URL: http://localhost:8080

      - name: Upload test coverage
        uses: codecov/codecov-action@v4
        if: always()
        with:
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
